global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-ms:8000']
        labels:
          app: 'auth-service'
          service: 'auth-service'
          application: 'auth-service'

  - job_name: 'device-service'
    static_configs:
      - targets: ['device-ms:8001']
        labels:
          app: 'device-service'
          service: 'device-service'
          application: 'device-service'

  - job_name: 'monitoring-service'
    static_configs:
      - targets: ['monitoring-ms:8002']
        labels:
          app: 'monitoring-service'
          service: 'monitoring-service'
          application: 'monitoring-service'

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq_broker:15692']
        labels:
          app: 'rabbitmq'
          service: 'rabbitmq'
          application: 'rabbitmq'
