services:
  auth_backend:
    build: .
    container_name: auth-ms
    environment:
      - SERVER_DB=postgresql_auth
      - REDIS_HOST=redis_auth
      - PYTHONUNBUFFERED=1
    ports:
      - 8000:8000
    depends_on:
      postgresql_auth:
        condition: service_healthy
      redis_auth:
        condition: service_healthy
    networks:
      - iot-network

  postgresql_auth:
    image: postgres:alpine
    container_name: postgresql_auth
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db_auth"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - iot-network
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis_auth:
    image: redis:alpine
    container_name: redis_auth
    ports:
      - 6379:6379
    networks:
      - iot-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  iot-network:
    name: iot-network
    driver: bridge

volumes:
  postgres_auth_data:
